# -*- coding: utf-8 -*-
"""project.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNiKSHaogB9pHP0RcJ94QLMqurW3jAnR
"""

import cv2
import os
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, GlobalAveragePooling2D
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D
from keras.layers.normalization import BatchNormalization
from keras.models import Model
import os
from google.colab import drive

drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd ./drive/MyDrive/My_data/project/Code/

pip install Augmentor

##DATA AUGMENTATION PAR
##RUN IT ONLY ONCE

import Augmentor
# #reading the images 
# p = Augmentor.Pipeline('./')

p.set_seed(123)

p.rotate(probability=0.7, max_left_rotation=5, max_right_rotation=5)
p.flip_random(probability=0.7)
p.scale(probability=0.7,scale_factor=1.15)

##p.shear(probability=0.7, max_shear_left=0.05,max_shear_right=0.05)

p.sample(5000)


## DEVIDE THE AUGMNENTED DATA
## TO TRAIN AND TEST
## RUN IT ONLY ONCE

files = os.listdir()
D = 0
N = 0
normal = []
abnormal = []
for i in range (0,len(files)):
    if (files[i][15] == 'N'):
        normal.append(files[i])
    else:
        abnormal.append(files[i])

random.seed(123)
randomlist1 = random.sample(range(0, len(normal)), 750)

random.seed(151)
randomlist2 = random.sample(range(0, len(abnormal)), 750)

for i in range (0,len(normal)):
    if i in randomlist1:
        shutil.move(normal[i],'./../validation/normal')
    else:
        shutil.move(normal[i],'./../train/normal')

for i in range (0,len(abnormal)):
    if i in randomlist2:
        shutil.move(abnormal[i],'./../validation/abnormal')
    else:
        shutil.move(abnormal[i],'./../train/abnormal')


